export const TRANSACTION_TYPES = { INCOME: "INCOME", EXPENSE: "EXPENSE" } as const;
export const TRANSACTION_STATUS = { PENDING: "PENDING", CONFIRMED: "CONFIRMED" } as const;
export const RECURRING_FREQUENCIES = { DAILY: "DAILY", WEEKLY: "WEEKLY", MONTHLY: "MONTHLY", YEARLY: "YEARLY", CUSTOM_DAYS: "CUSTOM_DAYS" } as const;
export const TRANSACTION_TYPES_ARRAY = Object.values(TRANSACTION_TYPES);
export const TRANSACTION_STATUS_ARRAY = Object.values(TRANSACTION_STATUS);
export const RECURRING_FREQUENCIES_ARRAY = Object.values(RECURRING_FREQUENCIES);