export const TRANSACTION_TYPES = { INCOME: "INCOME", EXPENSE: "EXPENSE" } as const;
export const TRANSACTION_STATUS = { PENDING: "PENDING", CONFIRMED: "CONFIRMED" } as const;
export const TRANSACTION_TYPES_ARRAY = Object.values(TRANSACTION_TYPES);
export const TRANSACTION_STATUS_ARRAY = Object.values(TRANSACTION_STATUS);